name: "Deploy WordPress"
description: "Deploy WordPress code to a server"
author: "rtCamp"
runs:
  using: "docker"
  image: "docker://ghcr.io/8ballsnl/action-deploy-wordpress:master"
branding:
  icon: "upload-cloud"
  color: "yellow"
